import type {
  DashboardEvolution,
  DashboardIncidents,
  DashboardLearning,
  DashboardOverview,
  DashboardSystem,
  DashboardTrading,
} from "@/lib/types";

const DEMO_GENERATED_AT = "2026-03-25T14:15:00.000Z";

export function buildDemoOverview(): DashboardOverview {
  return {
    generated_at: DEMO_GENERATED_AT,
    freshness: {
      state: "fresh",
      age_seconds: 12,
      generated_at: DEMO_GENERATED_AT,
      note: "Demo preview mode",
    },
    headline:
      "Single-VPS authority core is healthy, research loops are active, and live execution is still gated behind approvals.",
    summary_cards: [
      { label: "Production strategies", value: "4", tone: "good", hint: "2 equities, 2 options sleeves live-ready" },
      { label: "Pending approvals", value: "2", tone: "warn", hint: "Live rollout and config promotion waiting" },
      { label: "Market mode", value: "us", tone: "good", hint: "US equities + options deployment" },
      { label: "Learning docs", value: "128", tone: "good", hint: "Fresh research and post-mortems retained" },
      { label: "Ready insights", value: "9", tone: "good", hint: "Ready for governance review" },
      { label: "Principle memory", value: "34", tone: "good", hint: "Promoted, durable operating knowledge" },
      { label: "Active overrides", value: "1", tone: "warn", hint: "One guarded exposure override" },
    ],
    highlights: [
      "Discord owner control, dashboard monitoring, and governed research loops are online.",
      "The runtime is still in paper-first posture even though multiple sleeves are execution-ready.",
      "Codex work is queued behind governed approvals instead of acting as an unbounded control plane.",
      "Long-term memory remains separated from raw research intake so promotion stays explicit.",
    ],
    strategy: {
      candidates: 12,
      staging: 5,
      production: 4,
      active_production: true,
    },
    learning: {
      principles: 34,
      causal_cases: 91,
      document_count: 128,
      insight_count: 48,
      ready_insight_count: 9,
      quarantined_insight_count: 3,
      occupied_feature_cells: 22,
      feature_coverage_pct: 36.7,
      total_generations: 187,
    },
    system: {
      mode: "paper_live_guarded",
      risk_state: "normal",
      deployment_market_mode: "us",
      active_sleeves: ["equities", "options", "event"],
      market_calendar: "XNYS",
      market_timezone: "America/New_York",
      codex_queue_depth: 2,
      active_goals: 6,
      open_incidents: 1,
      pending_approvals: 2,
      active_overrides: 1,
      repo_root: "/opt/evoq",
    },
  };
}

export function buildDemoTrading(): DashboardTrading {
  return {
    generated_at: DEMO_GENERATED_AT,
    freshness: {
      state: "fresh",
      age_seconds: 14,
      generated_at: DEMO_GENERATED_AT,
      note: "Demo preview mode",
    },
    strategy_lab: {
      hypothesis_count: 17,
      spec_count: 8,
      paper_candidate_count: 5,
      paper_running_count: 3,
      live_candidate_count: 2,
      production_count: 4,
    },
    execution_readiness: {
      status: "guarded",
      trading_allowed: false,
      market_calendar: "XNYS",
      market_session_label: "Regular session",
      market_open: true,
      active_production_strategies: 4,
      active_trading_overrides: 1,
      open_provider_incidents: 1,
      latest_provider_health: "degraded",
      broker_snapshot_age_seconds: 22,
      reconciliation_status: "matched",
      reconciliation_halt_triggered: false,
      blocked_reasons: ["Two live-activation approvals are still unresolved for the options and event sleeves."],
      warnings: ["A temporary exposure override is capping gross notional until the latest event-risk review clears."],
    },
    allocation_policy: {
      policy_key: "us-multi-asset-v3",
      environment: "paper",
      scope: "portfolio",
      max_strategy_notional_pct: 0.12,
      max_gross_exposure_pct: 1.65,
      max_open_positions: 18,
      max_open_orders: 14,
      allow_short: true,
      allow_fractional: false,
      updated_at: "2026-03-25T12:30:00.000Z",
    },
    summary_cards: [
      { label: "Paper PnL", value: "+3.8%", tone: "good", hint: "30-day governed paper performance" },
      { label: "Gross exposure", value: "41%", tone: "neutral", hint: "inside current guarded envelope" },
      { label: "Activation approvals", value: "2", tone: "warn", hint: "required before live sleeves can unpause" },
      { label: "Options review", value: "2", tone: "warn", hint: "contracts inside the review window" },
    ],
    highlights: [
      "Execution is intentionally governed: research and paper sleeves keep running while live lanes stay paused behind approvals.",
      "US equities and options share the same allocation envelope but keep separate lifecycle review paths.",
      "The trading desk should explain why the system is not trading, not merely show a green or red lamp.",
    ],
    domain_states: [
      { domain: "research", is_paused: false, pending_approval_count: 0, override_count: 0, latest_reason: null },
      { domain: "paper-trading", is_paused: false, pending_approval_count: 0, override_count: 0, latest_reason: null },
      {
        domain: "live-equities",
        is_paused: true,
        pending_approval_count: 1,
        override_count: 0,
        latest_reason: "Awaiting owner approval on event-week allocation expansion.",
      },
      {
        domain: "live-options",
        is_paused: true,
        pending_approval_count: 1,
        override_count: 1,
        latest_reason: "Short-premium lane held until broker incident and margin check are cleared.",
      },
    ],
    latest_account_snapshot: {
      id: "acct-snap-001",
      provider_key: "ibkr",
      account_ref: "DU9123456",
      environment: "paper",
      equity: 428450.12,
      cash: 119240.48,
      buying_power: 602300.1,
      gross_exposure: 174210.65,
      net_exposure: 93240.25,
      positions_count: 6,
      open_orders_count: 4,
      source_captured_at: "2026-03-25T14:14:38.000Z",
      source_age_seconds: 22,
      created_at: "2026-03-25T14:14:40.000Z",
    },
    latest_reconciliation: {
      id: "recon-001",
      provider_key: "ibkr",
      account_ref: "DU9123456",
      environment: "paper",
      equity_delta_abs: 0,
      equity_delta_pct: 0,
      position_delta_count: 0,
      order_delta_count: 1,
      blocking_reason: null,
      halt_triggered: false,
      status: "matched",
      checked_at: "2026-03-25T14:12:00.000Z",
      created_at: "2026-03-25T14:12:02.000Z",
    },
    latest_broker_sync: {
      id: "broker-sync-001",
      provider_key: "ibkr",
      account_ref: "DU9123456",
      environment: "paper",
      broker_adapter: "interactive-brokers",
      sync_scope: "orders-and-positions",
      synced_orders_count: 4,
      synced_positions_count: 6,
      unmanaged_orders_count: 0,
      unmanaged_positions_count: 0,
      missing_internal_orders_count: 1,
      missing_internal_positions_count: 0,
      status: "completed_with_warnings",
      completed_at: "2026-03-25T14:13:16.000Z",
      created_at: "2026-03-25T14:12:59.000Z",
    },
    recent_market_sessions: [
      {
        id: "session-001",
        market_calendar: "XNYS",
        market_timezone: "America/New_York",
        session_label: "Regular session",
        is_market_open: true,
        trading_allowed: false,
        next_open_at: "2026-03-26T13:30:00.000Z",
        next_close_at: "2026-03-25T20:00:00.000Z",
        created_at: "2026-03-25T14:10:00.000Z",
      },
    ],
    active_provider_incidents: [
      {
        id: "provider-incident-001",
        provider_key: "ibkr",
        title: "Options chain Greeks lagging",
        severity: "medium",
        status: "investigating",
        detected_at: "2026-03-25T13:48:00.000Z",
        resolved_at: null,
      },
    ],
    recent_order_intents: [
      {
        id: "intent-001",
        strategy_spec_id: "spec-meanrev-01",
        provider_key: "ibkr",
        symbol: "AAPL",
        asset_type: "equity",
        instrument_key: "AAPL",
        position_effect: "open",
        side: "buy",
        quantity: 120,
        reference_price: 214.35,
        requested_notional: 25722,
        leg_count: 1,
        broker_adapter: "interactive-brokers",
        status: "queued",
        decision_reason: "Breakout sleeve passed signal and liquidity checks but waits on guarded live lane approval.",
        created_at: "2026-03-25T14:09:00.000Z",
      },
      {
        id: "intent-002",
        strategy_spec_id: "spec-premium-02",
        provider_key: "ibkr",
        symbol: "SPY 2026-04-17 530P",
        asset_type: "option",
        instrument_key: "SPY-20260417-530P",
        position_effect: "open",
        side: "sell",
        quantity: 3,
        reference_price: 8.45,
        requested_notional: 2535,
        leg_count: 1,
        broker_adapter: "interactive-brokers",
        status: "awaiting_approval",
        decision_reason: "Short-premium sleeve is margin-safe but still requires final event-risk approval.",
        created_at: "2026-03-25T14:06:00.000Z",
      },
    ],
    recent_order_records: [
      {
        id: "order-001",
        order_intent_id: "intent-000",
        broker_order_id: "IBKR-9001001",
        client_order_id: "EVOQ-001",
        parent_order_record_id: null,
        symbol: "MSFT",
        asset_type: "equity",
        instrument_key: "MSFT",
        position_effect: "open",
        side: "buy",
        quantity: 80,
        filled_quantity: 80,
        avg_fill_price: 421.22,
        leg_count: 1,
        status: "filled",
        submitted_at: "2026-03-25T13:31:00.000Z",
        broker_updated_at: "2026-03-25T13:31:12.000Z",
        created_at: "2026-03-25T13:31:12.000Z",
      },
      {
        id: "order-002",
        order_intent_id: "intent-002",
        broker_order_id: "IBKR-9001002",
        client_order_id: "EVOQ-002",
        parent_order_record_id: null,
        symbol: "SPY 2026-04-17 530P",
        asset_type: "option",
        instrument_key: "SPY-20260417-530P",
        position_effect: "open",
        side: "sell",
        quantity: 3,
        filled_quantity: 0,
        avg_fill_price: null,
        leg_count: 1,
        status: "held",
        submitted_at: "2026-03-25T14:06:10.000Z",
        broker_updated_at: "2026-03-25T14:06:12.000Z",
        created_at: "2026-03-25T14:06:12.000Z",
      },
    ],
    active_positions: [
      {
        id: "pos-001",
        strategy_spec_id: "spec-breakout-01",
        symbol: "MSFT",
        underlying_symbol: null,
        asset_type: "equity",
        instrument_key: "MSFT",
        direction: "long",
        quantity: 80,
        avg_entry_price: 421.22,
        market_price: 424.1,
        notional_value: 33928,
        realized_pnl: 0,
        unrealized_pnl: 230.4,
        status: "open",
        last_synced_at: "2026-03-25T14:14:40.000Z",
        created_at: "2026-03-25T13:31:12.000Z",
      },
      {
        id: "pos-002",
        strategy_spec_id: "spec-hedge-02",
        symbol: "QQQ 2026-04-17 460P",
        underlying_symbol: "QQQ",
        asset_type: "option",
        instrument_key: "QQQ-20260417-460P",
        direction: "long",
        quantity: 4,
        avg_entry_price: 6.15,
        market_price: 6.72,
        notional_value: 2688,
        realized_pnl: 0,
        unrealized_pnl: 228,
        status: "open",
        last_synced_at: "2026-03-25T14:14:40.000Z",
        created_at: "2026-03-24T17:40:00.000Z",
      },
      {
        id: "pos-003",
        strategy_spec_id: "spec-pairs-01",
        symbol: "NVDA",
        underlying_symbol: null,
        asset_type: "equity",
        instrument_key: "NVDA",
        direction: "short",
        quantity: 25,
        avg_entry_price: 901.4,
        market_price: 888.8,
        notional_value: 22220,
        realized_pnl: 0,
        unrealized_pnl: 315,
        status: "open",
        last_synced_at: "2026-03-25T14:14:40.000Z",
        created_at: "2026-03-24T16:18:00.000Z",
      },
    ],
    expiring_option_positions: [
      {
        id: "expiry-001",
        strategy_spec_id: "spec-hedge-02",
        symbol: "QQQ 2026-04-17 460P",
        underlying_symbol: "QQQ",
        instrument_key: "QQQ-20260417-460P",
        quantity: 4,
        direction: "long",
        expiration_date: "2026-04-17T20:00:00.000Z",
        days_to_expiry: 23,
        market_price: 6.72,
        unrealized_pnl: 228,
      },
      {
        id: "expiry-002",
        strategy_spec_id: "spec-income-01",
        symbol: "SPY 2026-04-03 520C",
        underlying_symbol: "SPY",
        instrument_key: "SPY-20260403-520C",
        quantity: 2,
        direction: "short",
        expiration_date: "2026-04-03T20:00:00.000Z",
        days_to_expiry: 9,
        market_price: 7.2,
        unrealized_pnl: -56,
      },
    ],
    recent_option_events: [
      {
        id: "option-event-001",
        event_type: "assignment-risk-review",
        symbol: "SPY 2026-04-03 520C",
        underlying_symbol: "SPY",
        quantity: 2,
        event_price: 7.2,
        cash_flow: null,
        state_applied: true,
        review_required: true,
        status: "open",
        occurred_at: "2026-03-25T13:55:00.000Z",
        notes: "Underlying moved into the upper guard band and triggered a pre-roll review.",
      },
      {
        id: "option-event-002",
        event_type: "dividend-check",
        symbol: "QQQ 2026-04-17 460P",
        underlying_symbol: "QQQ",
        quantity: 4,
        event_price: 6.72,
        cash_flow: 0,
        state_applied: true,
        review_required: false,
        status: "closed",
        occurred_at: "2026-03-25T12:21:00.000Z",
        notes: "No early-exercise edge detected under current carry assumptions.",
      },
    ],
    recent_specs: [
      {
        id: "spec-breakout-01",
        spec_code: "US-BRK-01",
        title: "Large-cap earnings breakout sleeve",
        target_market: "us",
        current_stage: "production",
        latest_backtest_gate: "pass",
        latest_paper_gate: "pass",
        created_at: "2026-03-18T10:00:00.000Z",
      },
      {
        id: "spec-premium-02",
        spec_code: "US-OPT-02",
        title: "Index short-premium carry sleeve",
        target_market: "us",
        current_stage: "live_candidate",
        latest_backtest_gate: "pass",
        latest_paper_gate: "review",
        created_at: "2026-03-20T08:40:00.000Z",
      },
    ],
    recent_backtests: [
      {
        id: "backtest-001",
        strategy_spec_id: "spec-breakout-01",
        dataset_range: "2019-01-01 to 2026-03-01",
        sample_size: 516,
        gate_result: "pass",
        total_return_pct: 27.4,
        sharpe_ratio: 1.61,
        max_drawdown_pct: 8.3,
        created_at: "2026-03-21T11:00:00.000Z",
      },
      {
        id: "backtest-002",
        strategy_spec_id: "spec-premium-02",
        dataset_range: "2021-01-01 to 2026-03-01",
        sample_size: 223,
        gate_result: "pass_with_margin_guard",
        total_return_pct: 18.9,
        sharpe_ratio: 1.32,
        max_drawdown_pct: 11.6,
        created_at: "2026-03-22T09:20:00.000Z",
      },
    ],
    recent_paper_runs: [
      {
        id: "paper-001",
        strategy_spec_id: "spec-breakout-01",
        deployment_label: "paper-us-breakout-a",
        monitoring_days: 21,
        gate_result: "pass",
        net_pnl_pct: 4.6,
        profit_factor: 1.48,
        max_drawdown_pct: 3.1,
        created_at: "2026-03-25T09:00:00.000Z",
      },
      {
        id: "paper-002",
        strategy_spec_id: "spec-premium-02",
        deployment_label: "paper-us-options-income-a",
        monitoring_days: 18,
        gate_result: "review",
        net_pnl_pct: 2.1,
        profit_factor: 1.22,
        max_drawdown_pct: 4.4,
        created_at: "2026-03-25T09:20:00.000Z",
      },
    ],
  };
}

export function buildDemoLearning(): DashboardLearning {
  return {
    generated_at: DEMO_GENERATED_AT,
    freshness: {
      state: "fresh",
      age_seconds: 19,
      generated_at: DEMO_GENERATED_AT,
      note: "Demo preview mode",
    },
    metrics: {
      document_count: 128,
      insight_count: 48,
      ready_insight_count: 9,
      quarantined_insight_count: 3,
    },
    summary_cards: [
      { label: "Principles", value: "34", tone: "good", hint: "promoted operating doctrine" },
      { label: "Causal cases", value: "91", tone: "good", hint: "durable failure and success post-mortems" },
      { label: "Feature coverage", value: "36.7%", tone: "good", hint: "occupied learning-map cells" },
      { label: "Source health", value: "92%", tone: "good", hint: "healthy or monitored sources" },
    ],
    highlights: [
      "The learning mesh retains documents and promoted insights separately so doctrine does not get polluted by raw intake.",
      "Research runs across market, strategy, infra, and post-mortem topics instead of only chasing immediate trade ideas.",
      "Promotion remains evidence-backed and quarantine is a visible first-class state.",
    ],
    sources: [
      {
        source_key: "news-wire",
        source_type: "news",
        health_status: "healthy",
        trust_score: 0.91,
        freshness_score: 0.95,
        last_validated_at: "2026-03-25T13:58:00.000Z",
        notes: "High-reliability macro and earnings feed.",
      },
      {
        source_key: "sec-filings",
        source_type: "filings",
        health_status: "healthy",
        trust_score: 0.97,
        freshness_score: 0.88,
        last_validated_at: "2026-03-25T12:40:00.000Z",
        notes: "Primary-source filings and statements.",
      },
      {
        source_key: "market-microstructure",
        source_type: "market-data",
        health_status: "monitor",
        trust_score: 0.83,
        freshness_score: 0.9,
        last_validated_at: "2026-03-25T14:00:00.000Z",
        notes: "Intermittent quote enrichment lag during the US open.",
      },
      {
        source_key: "operator-journal",
        source_type: "internal",
        health_status: "healthy",
        trust_score: 0.88,
        freshness_score: 0.78,
        last_validated_at: "2026-03-24T23:00:00.000Z",
        notes: "Owner instructions and governed feedback notes.",
      },
    ],
    recent_documents: [
      {
        id: "doc-001",
        codex_run_id: "codex-learn-001",
        workflow_run_id: "wf-learn-001",
        source_key: "news-wire",
        title: "Semiconductor capex cycle note",
        summary: "Cross-source synthesis on AI capex resilience and second-order supplier impact.",
        status: "retained",
        source_type: "news",
        supervisor_loop_key: "loop-learning-us-macro",
        citation_count: 12,
        evidence_count: 8,
        confidence: 0.84,
        created_at: "2026-03-25T13:42:00.000Z",
      },
      {
        id: "doc-002",
        codex_run_id: "codex-learn-002",
        workflow_run_id: "wf-learn-002",
        source_key: "sec-filings",
        title: "Broker margin policy changes digest",
        summary: "Durable note on options margin tightening and its impact on sleeve sizing.",
        status: "retained",
        source_type: "filings",
        supervisor_loop_key: "loop-learning-execution-risk",
        citation_count: 6,
        evidence_count: 4,
        confidence: 0.93,
        created_at: "2026-03-25T12:58:00.000Z",
      },
      {
        id: "doc-003",
        codex_run_id: "codex-learn-003",
        workflow_run_id: "wf-learn-003",
        source_key: "operator-journal",
        title: "Owner preference drift check",
        summary: "Comparison between current governed posture and last approved owner intent.",
        status: "review",
        source_type: "internal",
        supervisor_loop_key: "loop-learning-governance",
        citation_count: 3,
        evidence_count: 2,
        confidence: 0.78,
        created_at: "2026-03-25T11:40:00.000Z",
      },
    ],
    recent_insights: [
      {
        id: "insight-001",
        document_id: "doc-001",
        codex_run_id: "codex-learn-001",
        workflow_run_id: "wf-learn-001",
        supervisor_loop_key: "loop-learning-us-macro",
        topic_key: "us/semis/capex",
        title: "Second-order suppliers react later than mega-cap leaders",
        summary: "Useful for staggered entry and exit planning in the large-cap breakout sleeve.",
        status: "ready",
        promotion_state: "ready_for_review",
        evidence_count: 8,
        citation_count: 12,
        confidence: 0.86,
        quarantine_reason: null,
        created_at: "2026-03-25T13:50:00.000Z",
      },
      {
        id: "insight-002",
        document_id: "doc-002",
        codex_run_id: "codex-learn-002",
        workflow_run_id: "wf-learn-002",
        supervisor_loop_key: "loop-learning-execution-risk",
        topic_key: "us/options/margin",
        title: "Short-premium sleeves need tighter pre-event margin buffers",
        summary: "Promote into execution doctrine only after broker policy confirmation.",
        status: "quarantined",
        promotion_state: "blocked",
        evidence_count: 4,
        citation_count: 6,
        confidence: 0.73,
        quarantine_reason: "Requires broker-side policy confirmation after the latest margin bulletin.",
        created_at: "2026-03-25T13:02:00.000Z",
      },
      {
        id: "insight-003",
        document_id: "doc-003",
        codex_run_id: "codex-learn-003",
        workflow_run_id: "wf-learn-003",
        supervisor_loop_key: "loop-learning-governance",
        topic_key: "governance/owner-intent",
        title: "Owner prefers manual confirmation on cross-asset leverage expansion",
        summary: "Keep leverage-lane proposals in governed approval instead of auto-promotion.",
        status: "ready",
        promotion_state: "ready_for_review",
        evidence_count: 2,
        citation_count: 3,
        confidence: 0.81,
        quarantine_reason: null,
        created_at: "2026-03-25T11:46:00.000Z",
      },
    ],
    supervisor_loops: [
      {
        loop_key: "loop-learning-us-macro",
        workflow_code: "learning_us_macro",
        domain: "learning",
        display_name: "US Macro Research Loop",
        execution_mode: "active",
        is_enabled: true,
        cadence_seconds: 1800,
        next_due_at: "2026-03-25T14:30:00.000Z",
        last_completed_at: "2026-03-25T14:00:00.000Z",
        last_status: "completed",
        failure_streak: 0,
        last_error: null,
      },
      {
        loop_key: "loop-learning-execution-risk",
        workflow_code: "learning_execution_risk",
        domain: "learning",
        display_name: "Execution Risk Learning Loop",
        execution_mode: "active",
        is_enabled: true,
        cadence_seconds: 2700,
        next_due_at: "2026-03-25T14:45:00.000Z",
        last_completed_at: "2026-03-25T14:00:00.000Z",
        last_status: "completed_with_review",
        failure_streak: 0,
        last_error: null,
      },
      {
        loop_key: "loop-learning-governance",
        workflow_code: "learning_governance_memory",
        domain: "learning",
        display_name: "Governance Memory Loop",
        execution_mode: "active",
        is_enabled: true,
        cadence_seconds: 3600,
        next_due_at: "2026-03-25T15:00:00.000Z",
        last_completed_at: "2026-03-25T14:00:00.000Z",
        last_status: "completed",
        failure_streak: 0,
        last_error: null,
      },
    ],
  };
}

export function buildDemoEvolution(): DashboardEvolution {
  return {
    generated_at: DEMO_GENERATED_AT,
    freshness: {
      state: "fresh",
      age_seconds: 26,
      generated_at: DEMO_GENERATED_AT,
      note: "Demo preview mode",
    },
    metrics: {
      proposal_count: 11,
      ready_for_review_count: 3,
      active_canary_count: 2,
      promoted_count: 8,
      rolled_back_count: 1,
    },
    summary_cards: [
      { label: "Promotion rate", value: "72%", tone: "good", hint: "recent proposals promoted without rollback" },
      { label: "Objective drift", value: "0.11", tone: "good", hint: "mean drift score across current canaries" },
      { label: "Review backlog", value: "3", tone: "warn", hint: "governance attention required" },
      { label: "Rollback events", value: "1", tone: "warn", hint: "contained inside the last 14 days" },
    ],
    highlights: [
      "Evolution is treated as a governed control plane with proposals, canaries, and explicit promotion decisions.",
      "Codex runs are separated from final promotion so the system can improve without silently mutating itself.",
      "Rollback evidence stays visible because self-improvement without memory of failure is not trustworthy.",
    ],
    recent_proposals: [
      {
        id: "proposal-001",
        title: "Tighten options sleeve margin pre-check",
        target_surface: "trading",
        proposal_kind: "risk_policy",
        proposal_state: "ready_for_review",
        risk_summary: "Reduces live margin blow-up risk at the cost of lower fill rate.",
        codex_run_id: "codex-evo-001",
        workflow_run_id: "wf-evo-001",
        created_at: "2026-03-25T13:18:00.000Z",
      },
      {
        id: "proposal-002",
        title: "Promote learning-loop evidence threshold for doctrine updates",
        target_surface: "learning",
        proposal_kind: "governance",
        proposal_state: "canary_running",
        risk_summary: "Improves memory quality while reducing low-signal doctrine churn.",
        codex_run_id: "codex-evo-002",
        workflow_run_id: "wf-evo-002",
        created_at: "2026-03-25T12:42:00.000Z",
      },
      {
        id: "proposal-003",
        title: "Refactor broker sync retry path",
        target_surface: "system",
        proposal_kind: "infra",
        proposal_state: "promoted",
        risk_summary: "Should reduce false-positive incident noise during provider blips.",
        codex_run_id: "codex-evo-003",
        workflow_run_id: "wf-evo-003",
        created_at: "2026-03-24T21:18:00.000Z",
      },
    ],
    recent_canary_runs: [
      {
        id: "canary-001",
        proposal_id: "proposal-002",
        lane_type: "shadow",
        environment: "paper",
        traffic_pct: 50,
        objective_drift_score: 0.08,
        rollback_ready: true,
        status: "running",
        completed_at: null,
        created_at: "2026-03-25T13:06:00.000Z",
      },
      {
        id: "canary-002",
        proposal_id: "proposal-001",
        lane_type: "guarded",
        environment: "paper",
        traffic_pct: 25,
        objective_drift_score: 0.14,
        rollback_ready: true,
        status: "running",
        completed_at: null,
        created_at: "2026-03-25T13:24:00.000Z",
      },
    ],
    recent_promotion_decisions: [
      {
        id: "promotion-001",
        proposal_id: "proposal-003",
        decision: "promote",
        decided_by: "evolution-council",
        rationale: "Infra improvement reduced sync noise in canary without raising incident pressure.",
        decided_at: "2026-03-24T23:50:00.000Z",
      },
      {
        id: "promotion-002",
        proposal_id: "proposal-004",
        decision: "rollback",
        decided_by: "evolution-council",
        rationale: "Signal ranking tweak increased turnover and degraded paper slippage tolerance.",
        decided_at: "2026-03-23T18:18:00.000Z",
      },
    ],
    recent_workflows: [
      {
        id: "wf-evo-001",
        workflow_code: "evolution_margin_guard",
        workflow_name: "Margin Guard Review",
        workflow_family: "evolution",
        owner_role: "council",
        status: "awaiting_review",
        started_at: "2026-03-25T13:12:00.000Z",
        ended_at: null,
        latest_event_summary: "Proposal assembled and routed to governed review.",
      },
      {
        id: "wf-evo-002",
        workflow_code: "evolution_learning_gate",
        workflow_name: "Learning Gate Threshold Review",
        workflow_family: "evolution",
        owner_role: "council",
        status: "running",
        started_at: "2026-03-25T12:40:00.000Z",
        ended_at: null,
        latest_event_summary: "Canary metrics remain inside the promotion envelope.",
      },
      {
        id: "wf-evo-003",
        workflow_code: "evolution_sync_refactor",
        workflow_name: "Broker Sync Retry Refactor",
        workflow_family: "evolution",
        owner_role: "worker",
        status: "completed",
        started_at: "2026-03-24T20:05:00.000Z",
        ended_at: "2026-03-24T23:45:00.000Z",
        latest_event_summary: "Promoted after passing canary and smoke checks.",
      },
    ],
    recent_codex_runs: [
      {
        id: "codex-evo-001",
        status: "completed",
        worker_class: "research-synthesis",
        execution_mode: "governed",
        strategy_mode: "evolution",
        objective: "Draft a governed change set for tighter options margin pre-checks.",
        current_attempt: 3,
        max_iterations: 5,
        queued_at: "2026-03-25T12:58:00.000Z",
        completed_at: "2026-03-25T13:10:00.000Z",
        last_error: null,
      },
      {
        id: "codex-evo-002",
        status: "running",
        worker_class: "policy-audit",
        execution_mode: "governed",
        strategy_mode: "evolution",
        objective: "Assess doctrine promotion thresholds against recent quarantined insights.",
        current_attempt: 2,
        max_iterations: 4,
        queued_at: "2026-03-25T12:44:00.000Z",
        completed_at: null,
        last_error: null,
      },
      {
        id: "codex-evo-003",
        status: "completed",
        worker_class: "implementation",
        execution_mode: "governed",
        strategy_mode: "evolution",
        objective: "Refactor broker sync retry handling to reduce false incident noise.",
        current_attempt: 4,
        max_iterations: 6,
        queued_at: "2026-03-24T20:18:00.000Z",
        completed_at: "2026-03-24T22:54:00.000Z",
        last_error: null,
      },
    ],
    supervisor_loops: [
      {
        loop_key: "loop-evolution-governance",
        workflow_code: "evolution_governance",
        domain: "evolution",
        display_name: "Governed Evolution Loop",
        execution_mode: "active",
        is_enabled: true,
        cadence_seconds: 3600,
        next_due_at: "2026-03-25T15:00:00.000Z",
        last_completed_at: "2026-03-25T14:00:00.000Z",
        last_status: "completed",
        failure_streak: 0,
        last_error: null,
      },
      {
        loop_key: "loop-evolution-canary",
        workflow_code: "evolution_canary_review",
        domain: "evolution",
        display_name: "Canary Review Loop",
        execution_mode: "active",
        is_enabled: true,
        cadence_seconds: 1800,
        next_due_at: "2026-03-25T14:30:00.000Z",
        last_completed_at: "2026-03-25T14:00:00.000Z",
        last_status: "completed_with_review",
        failure_streak: 0,
        last_error: null,
      },
    ],
  };
}

export function buildDemoSystem(): DashboardSystem {
  return {
    generated_at: DEMO_GENERATED_AT,
    freshness: {
      state: "fresh",
      age_seconds: 18,
      generated_at: DEMO_GENERATED_AT,
      note: "Demo preview mode",
    },
    summary_cards: [
      { label: "Providers", value: "4", tone: "good", hint: "market, broker, memory, and relay surfaces" },
      { label: "Active loops", value: "8", tone: "good", hint: "enabled active supervisor loops" },
      { label: "Config proposals", value: "2", tone: "warn", hint: "pending governed changes" },
      { label: "Owner preferences", value: "6", tone: "good", hint: "captured intent and safety posture" },
      { label: "Open incidents", value: "1", tone: "warn", hint: "watch before live promotion" },
    ],
    highlights: [
      "The authority core keeps runtime config, owner preferences, and governed change history visible in one place.",
      "System state should explain whether the stack is trustworthy before the owner acts through Discord.",
      "Single-VPS operation remains the default posture; worker scale-out is optional, not required.",
    ],
    providers: [
      {
        provider_key: "ibkr",
        display_name: "Interactive Brokers",
        health_status: "monitor",
        api_style: "broker",
        is_primary: true,
        base_url: "https://api.ibkr.local",
      },
      {
        provider_key: "market-data",
        display_name: "Market Data Fabric",
        health_status: "healthy",
        api_style: "market-data",
        is_primary: true,
        base_url: "https://market-data.internal",
      },
      {
        provider_key: "discord",
        display_name: "Discord Relay",
        health_status: "healthy",
        api_style: "im-relay",
        is_primary: true,
        base_url: "https://discord-relay.internal",
      },
      {
        provider_key: "memory-store",
        display_name: "Memory Store",
        health_status: "healthy",
        api_style: "memory",
        is_primary: true,
        base_url: "postgres://authority-core/memory",
      },
    ],
    supervisor_loops: [
      {
        loop_key: "loop-runtime-heartbeat",
        workflow_code: "system_runtime_heartbeat",
        domain: "system",
        display_name: "Runtime Heartbeat Loop",
        execution_mode: "active",
        is_enabled: true,
        cadence_seconds: 60,
        next_due_at: "2026-03-25T14:16:00.000Z",
        last_completed_at: "2026-03-25T14:15:00.000Z",
        last_status: "completed",
        failure_streak: 0,
        last_error: null,
      },
      {
        loop_key: "loop-broker-sync",
        workflow_code: "system_broker_sync",
        domain: "trading",
        display_name: "Broker Sync Loop",
        execution_mode: "active",
        is_enabled: true,
        cadence_seconds: 120,
        next_due_at: "2026-03-25T14:17:00.000Z",
        last_completed_at: "2026-03-25T14:15:00.000Z",
        last_status: "completed_with_warnings",
        failure_streak: 0,
        last_error: null,
      },
      {
        loop_key: "loop-owner-intent",
        workflow_code: "system_owner_intent_sync",
        domain: "system",
        display_name: "Owner Intent Sync",
        execution_mode: "active",
        is_enabled: true,
        cadence_seconds: 900,
        next_due_at: "2026-03-25T14:30:00.000Z",
        last_completed_at: "2026-03-25T14:00:00.000Z",
        last_status: "completed",
        failure_streak: 0,
        last_error: null,
      },
      {
        loop_key: "loop-dashboard-aggregator",
        workflow_code: "system_dashboard_aggregator",
        domain: "system",
        display_name: "Dashboard Aggregator",
        execution_mode: "active",
        is_enabled: true,
        cadence_seconds: 30,
        next_due_at: "2026-03-25T14:15:30.000Z",
        last_completed_at: "2026-03-25T14:15:00.000Z",
        last_status: "completed",
        failure_streak: 0,
        last_error: null,
      },
    ],
    recent_workflows: [
      {
        id: "wf-system-001",
        workflow_code: "system_relay_health",
        workflow_name: "Relay Health Audit",
        workflow_family: "system",
        owner_role: "core",
        status: "completed",
        started_at: "2026-03-25T13:52:00.000Z",
        ended_at: "2026-03-25T13:55:00.000Z",
        latest_event_summary: "Discord relay health stayed green across command and approval paths.",
      },
      {
        id: "wf-system-002",
        workflow_code: "system_config_review",
        workflow_name: "Runtime Config Review",
        workflow_family: "system",
        owner_role: "core",
        status: "awaiting_approval",
        started_at: "2026-03-25T13:18:00.000Z",
        ended_at: null,
        latest_event_summary: "Two config promotions are waiting for governed approval.",
      },
      {
        id: "wf-system-003",
        workflow_code: "system_broker_sync",
        workflow_name: "Broker Sync",
        workflow_family: "trading",
        owner_role: "core",
        status: "completed_with_warnings",
        started_at: "2026-03-25T14:12:00.000Z",
        ended_at: "2026-03-25T14:13:16.000Z",
        latest_event_summary: "One internal order mapping still requires reconciliation.",
      },
    ],
    recent_codex_runs: [
      {
        id: "codex-system-001",
        status: "completed",
        worker_class: "research-synthesis",
        execution_mode: "governed",
        strategy_mode: "system",
        objective: "Summarize runtime drift between owner preferences and active config.",
        current_attempt: 2,
        max_iterations: 3,
        queued_at: "2026-03-25T12:50:00.000Z",
        completed_at: "2026-03-25T13:02:00.000Z",
        last_error: null,
      },
      {
        id: "codex-system-002",
        status: "running",
        worker_class: "implementation",
        execution_mode: "governed",
        strategy_mode: "system",
        objective: "Draft a safer retry policy for provider health checks.",
        current_attempt: 1,
        max_iterations: 4,
        queued_at: "2026-03-25T13:58:00.000Z",
        completed_at: null,
        last_error: null,
      },
    ],
    runtime_config: [
      {
        target_type: "runtime",
        target_key: "deployment_market_mode",
        display_name: "Deployment Market Mode",
        category: "market",
        risk_level: "medium",
        is_mutable: false,
        requires_restart: true,
        updated_at: "2026-03-24T18:00:00.000Z",
        updated_by: "owner",
        value_preview: "us",
        preview_lines: ["deployment_market_mode=us", "single deployment targets one market at a time"],
        contains_sensitive_fields: false,
      },
      {
        target_type: "runtime",
        target_key: "codex_max_parallel_runs",
        display_name: "Codex Parallelism",
        category: "workers",
        risk_level: "medium",
        is_mutable: true,
        requires_restart: false,
        updated_at: "2026-03-24T18:20:00.000Z",
        updated_by: "governance",
        value_preview: "3",
        preview_lines: ["codex_max_parallel_runs=3", "guarded for single-VPS memory budget"],
        contains_sensitive_fields: false,
      },
      {
        target_type: "runtime",
        target_key: "paper_live_gate_mode",
        display_name: "Paper / Live Gate",
        category: "trading",
        risk_level: "high",
        is_mutable: true,
        requires_restart: false,
        updated_at: "2026-03-25T11:30:00.000Z",
        updated_by: "governance",
        value_preview: "paper_live_guarded",
        preview_lines: ["paper_live_gate_mode=paper_live_guarded", "live activation always requires governed approval"],
        contains_sensitive_fields: false,
      },
    ],
    pending_config_proposals: [
      {
        id: "cfg-proposal-001",
        target_type: "runtime",
        target_key: "options_margin_buffer_pct",
        display_name: "Options Margin Buffer",
        category: "risk",
        requested_by: "evolution-council",
        change_summary: "Raise the pre-trade margin buffer from 18% to 24% for short-premium sleeves.",
        risk_level: "high",
        requires_approval: true,
        approval_request_id: "approval-002",
        status: "awaiting_approval",
        created_at: "2026-03-25T13:20:00.000Z",
      },
      {
        id: "cfg-proposal-002",
        target_type: "runtime",
        target_key: "learning_promotion_evidence_min",
        display_name: "Learning Promotion Evidence Minimum",
        category: "learning",
        requested_by: "evolution-council",
        change_summary: "Increase minimum evidence count from 2 to 3 before insight promotion.",
        risk_level: "medium",
        requires_approval: true,
        approval_request_id: "approval-001",
        status: "proposed",
        created_at: "2026-03-25T12:44:00.000Z",
      },
    ],
    recent_config_revisions: [
      {
        id: "cfg-revision-001",
        target_type: "runtime",
        target_key: "codex_max_parallel_runs",
        display_name: "Codex Parallelism",
        change_summary: "Reduced from 4 to 3 to preserve dashboard and broker sync headroom on a single VPS.",
        applied_by: "governance",
        applied_at: "2026-03-24T18:20:00.000Z",
      },
      {
        id: "cfg-revision-002",
        target_type: "runtime",
        target_key: "paper_live_gate_mode",
        display_name: "Paper / Live Gate",
        change_summary: "Locked live posture behind approvals after rollout review.",
        applied_by: "owner",
        applied_at: "2026-03-25T11:30:00.000Z",
      },
    ],
    owner_preferences: [
      {
        preference_key: "owner_risk_bias",
        display_name: "Owner Risk Bias",
        scope: "global",
        updated_by: "owner",
        updated_at: "2026-03-24T21:00:00.000Z",
        value_preview: "moderately_aggressive",
        preview_lines: ["risk_bias=moderately_aggressive", "cross-asset leverage expansion still needs manual confirmation"],
        contains_sensitive_fields: false,
      },
      {
        preference_key: "owner_market_focus",
        display_name: "Market Focus",
        scope: "deployment",
        updated_by: "owner",
        updated_at: "2026-03-24T21:02:00.000Z",
        value_preview: "us",
        preview_lines: ["deployment focus=us", "support for CN mode remains available at deployment time"],
        contains_sensitive_fields: false,
      },
      {
        preference_key: "owner_notification_window",
        display_name: "Notification Window",
        scope: "discord",
        updated_by: "owner",
        updated_at: "2026-03-24T21:05:00.000Z",
        value_preview: "08:00-23:00 HKT",
        preview_lines: ["quiet hours respected unless a trading halt or approval gate is hit"],
        contains_sensitive_fields: false,
      },
    ],
  };
}

export function buildDemoIncidents(): DashboardIncidents {
  return {
    generated_at: DEMO_GENERATED_AT,
    freshness: {
      state: "fresh",
      age_seconds: 16,
      generated_at: DEMO_GENERATED_AT,
      note: "Demo preview mode",
    },
    summary_cards: [
      { label: "Open incidents", value: "1", tone: "warn", hint: "one provider issue still under watch" },
      { label: "Pending approvals", value: "2", tone: "warn", hint: "live posture and config promotion are gated" },
      { label: "Risk state", value: "normal", tone: "good", hint: "no portfolio-wide halt is active" },
      { label: "Active overrides", value: "1", tone: "warn", hint: "temporary exposure override still applies" },
    ],
    highlights: [
      "The incident desk is meant to support decisions, not just show alarms.",
      "Approval backlog is treated as operational pressure because it directly changes whether the system can evolve or trade.",
      "Incident visibility stays close to governance so the owner can judge risk and action in one place.",
    ],
    active_incidents: [
      {
        id: "incident-001",
        title: "IBKR options chain Greeks lagging",
        summary:
          "Quote enrichment is delayed for some SPY and QQQ chains during the open. Paper monitoring remains safe, but live options promotion stays paused.",
        severity: "medium",
        status: "investigating",
        created_at: "2026-03-25T13:48:00.000Z",
      },
    ],
    recent_incidents: [
      {
        id: "incident-001",
        title: "IBKR options chain Greeks lagging",
        summary: "Quote enrichment delay during the US open.",
        severity: "medium",
        status: "investigating",
        created_at: "2026-03-25T13:48:00.000Z",
      },
      {
        id: "incident-002",
        title: "Broker sync missing one internal order mapping",
        summary: "A filled order was recovered but still needs one internal correlation update.",
        severity: "low",
        status: "monitoring",
        created_at: "2026-03-25T13:16:00.000Z",
      },
      {
        id: "incident-003",
        title: "Learning promotion backlog elevated",
        summary: "Ready insight count spiked after macro and margin research runs.",
        severity: "low",
        status: "open",
        created_at: "2026-03-25T12:10:00.000Z",
      },
      {
        id: "incident-004",
        title: "Provider heartbeat jitter",
        summary: "Resolved after retry and queue smoothing changes.",
        severity: "low",
        status: "resolved",
        created_at: "2026-03-24T20:55:00.000Z",
      },
    ],
    pending_approvals: [
      {
        id: "approval-001",
        approval_type: "config_promotion",
        subject_id: "cfg-proposal-002",
        requested_by: "evolution-council",
        risk_level: "medium",
        decision_status: "pending",
        created_at: "2026-03-25T12:44:00.000Z",
      },
      {
        id: "approval-002",
        approval_type: "live_activation",
        subject_id: "options-live-lane",
        requested_by: "trading-council",
        risk_level: "high",
        decision_status: "pending",
        created_at: "2026-03-25T13:24:00.000Z",
      },
    ],
  };
}
